version: '3.7'

services:
  neo4j:
    image: neo4j:latest
    container_name: "neo-truist" 
    volumes:
      - C:\Users\rohit\Desktop\Truist_sprint\neo4j\data:/data
      - C:\Users\rohit\Desktop\Truist_sprint\neo4j\import:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=true
      - apoc.export.file.enabled=true
      - apoc.export.json.all=true
    networks:
      - truist_proj_net
       
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "jupyterlab-truist"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/truist_proj
    links:
      - neo4j
    networks:
      - truist_proj_net

networks:
  truist_proj_net: 